/*
 * generated by Xtext
 */
package org.xtext.lwc.instances.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class InstancesUiModule extends org.xtext.lwc.instances.ui.AbstractInstancesUiModule {
	public InstancesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
