/*
 * generated by Xtext
 */
package org.xtext.lwc.instances;

import org.eclipse.xtext.xbase.typing.ITypeProvider;
import org.xtext.lwc.instances.typesystem.InstancesTypeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class InstancesRuntimeModule extends org.xtext.lwc.instances.AbstractInstancesRuntimeModule {
	@Override
	public Class<? extends ITypeProvider> bindITypeProvider() {
		return InstancesTypeProvider.class;
	}
	
	
}
