/*
* generated by Xtext
*/
package org.xtext.lwc.instances.ui.contentassist;

import org.xtext.lwc.instances.ui.contentassist.AbstractInstancesProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class InstancesProposalProvider extends AbstractInstancesProposalProvider {

}
