/*
* generated by Xtext
*/
package org.xtext.lwc.instances.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.lwc.instances.services.InstancesGrammarAccess;

public class InstancesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private InstancesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.lwc.instances.parser.antlr.internal.InternalInstancesParser createParser(XtextTokenStream stream) {
		return new org.xtext.lwc.instances.parser.antlr.internal.InternalInstancesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Instance";
	}
	
	public InstancesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(InstancesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
