/*
* generated by Xtext
*/
package org.xtext.lwc.instances;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class InstancesUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.lwc.instances.ui.internal.InstancesActivator.getInstance().getInjector("org.xtext.lwc.instances.Instances");
	}
	
}
